version: '3.7'
services:
  database:
    image: postgres:12-alpine
    env_file:
      - ./.env
  app:
    tty: true 
    stdin_open: true
    build: .
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - database
